// Pure derivation for the docs category listing pages (comp: 08
// Docs.html Category view, `.plist`/`.prow`). Extracted from
// SectionPageList.astro so the ordering/exclusion rules are testable
// under plain `node --test` (scripts/test/section-pages.test.mjs) —
// the handoff's rule: listing rows are DERIVED from the content
// collection, never hand-maintained.

/**
 * Derive ordered listing rows for one docs section.
 *
 * @param {Array<{id: string, filePath?: string, data: {title?: string,
 *   description?: string, sidebar?: {order?: number, hidden?: boolean}}}>} entries
 *   Entries from `getCollection('docs')` (already filtered or not — the
 *   function filters to the section itself).
 * @param {string} section  Section slug, e.g. "concepts".
 * @returns {Array<{ord: string, href: string, title: string,
 *   description: string, filename: string}>}
 *
 * Rules (mirroring Starlight's autogenerated sidebar so the list and the
 * sidebar never disagree):
 * - only entries under `docs/<section>/`;
 * - the section's own index page (`docs/<section>`) and any
 *   `sidebar.hidden` entry are excluded;
 * - sorted by nesting depth first (top-level pages before `api/`
 *   sub-pages, matching the sidebar's trailing nested group), then
 *   `sidebar.order` ascending (missing order sorts last), then slug;
 * - `ord` is the zero-based row number, zero-padded ("00", "01", …) —
 *   comp: `String(i).padStart(2, "0")`;
 * - `filename` is "<section>/<file>.mdx" derived from filePath when
 *   available, else from the id.
 */
export function deriveSectionRows(entries, section) {
	const prefix = `docs/${section}/`;
	const rows = entries
		.filter((e) => e.id.startsWith(prefix))
		.filter((e) => !e.data?.sidebar?.hidden)
		.map((e) => {
			const rel = e.id.slice(prefix.length);
			return {
				id: e.id,
				depth: rel.split('/').length,
				order: e.data?.sidebar?.order ?? Number.POSITIVE_INFINITY,
				title: e.data?.title ?? rel,
				description: e.data?.description ?? '',
				filename: e.filePath
					? `${section}/${e.filePath.split(`/docs/${section}/`).pop()}`
					: `${section}/${rel}.mdx`,
			};
		})
		.sort(
			(a, b) =>
				a.depth - b.depth || a.order - b.order || a.id.localeCompare(b.id),
		);
	return rows.map((r, i) => ({
		ord: String(i).padStart(2, '0'),
		href: `/${r.id}/`,
		title: r.title,
		description: r.description,
		filename: r.filename,
	}));
}
