// AUTO-GENERATED by bench/build_data.py — do not edit by hand.
// Regenerate after a new sweep:  python3 bench/build_data.py

export interface HwRow { label: string; value: string }
export interface RosterRow {
  id: string
  hfRepo: string
  caps: string[]
  params: string
  kv: string
  spec: string
  gb: number | null
  dec: number | null
  pf: number | null
  acc: number | null
  note: string
  measured: boolean
}

export const ROSTER_DATE = "2026-06-19"
export const ROSTER_MEASURED = 26
export const ROSTER_TOTAL = 26

export const HARDWARE: HwRow[] = [
  {
    "label": "SoC",
    "value": "AMD Ryzen AI Max+ 395 \u2014 Strix Halo (Zen 5, 16C/28T)"
  },
  {
    "label": "iGPU",
    "value": "Radeon 8060S \u2014 RDNA 3.5, gfx1151 \u00b7 Vulkan-capable"
  },
  {
    "label": "NPU",
    "value": "AMD XDNA \u2014 amdxdna driver"
  },
  {
    "label": "Memory",
    "value": "128 GB unified LPDDR5X \u00b7 ~96 GB GPU-addressable (GTT) \u00b7 UMA"
  },
  {
    "label": "Host",
    "value": "Proxmox LXC \u00b7 Ubuntu 24.04 \u00b7 kernel 7.0.6"
  },
  {
    "label": "Model store",
    "value": "/mnt/ai-models \u00b7 ZFS"
  }
]

export const BINARY: HwRow[] = [
  {
    "label": "hal0",
    "value": "v0.5.0a1 \u00b7 llama-server provider (OpenAI /v1/*)"
  },
  {
    "label": "Container",
    "value": "ghcr.io/hal0ai/amd-strix-halo-toolboxes:rocm-7.2.4-rocmfp4-server"
  },
  {
    "label": "llama.cpp",
    "value": "build b9219-1faa48eef \u00b7 rocmfp4 fork (draft-mtp speculative)"
  },
  {
    "label": "ROCm",
    "value": "7.2.4"
  }
]

export const ROSTER: RosterRow[] = [
  {
    "id": "chadrock-35b-ace-saber",
    "hfRepo": "jcbtc/chadrock-35b-ace-saber-rocmfp4-mtp",
    "caps": [
      "mtp",
      "vision"
    ],
    "params": "35B-A3B",
    "kv": "f16",
    "spec": "draft-mtp",
    "gb": 19.0,
    "dec": 100.5,
    "pf": 902.9,
    "acc": 83.1,
    "note": "vision;",
    "measured": true
  },
  {
    "id": "qwen3.6-35b-a3b-crown-halo-mtp-dynamic",
    "hfRepo": "jcbtc/qwen3.6-35b-a3b-crown-halo-mtp-dynamic",
    "caps": [
      "mtp",
      "vision"
    ],
    "params": "35B-A3B",
    "kv": "f16",
    "spec": "draft-mtp",
    "gb": 22.6,
    "dec": 84.4,
    "pf": 872.5,
    "acc": 90.9,
    "note": "vision;",
    "measured": true
  },
  {
    "id": "chadrock3.6-27b-pi-agent-rocmfp4-mtp",
    "hfRepo": "jcbtc/chadrock3.6-27b-pi-agent-rocmfp4-mtp",
    "caps": [
      "mtp",
      "tools"
    ],
    "params": "27B dense",
    "kv": "q8",
    "spec": "draft-mtp",
    "gb": 14.8,
    "dec": 35.5,
    "pf": 301.4,
    "acc": 79.8,
    "note": "",
    "measured": true
  },
  {
    "id": "qwopus3-6-27b-v2-mtp-bf16-to-rocmfp4-strix-lean",
    "hfRepo": "",
    "caps": [
      "mtp"
    ],
    "params": "27B dense",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 14.8,
    "dec": 31.6,
    "pf": 310.3,
    "acc": 70.3,
    "note": "",
    "measured": true
  },
  {
    "id": "gemma-4-12B-agentic-fable5",
    "hfRepo": "yuxinlu1/gemma-4-12B-agentic-fable5-composer2.5-v2-3.5x-tau2-GGUF",
    "caps": [
      "tools"
    ],
    "params": "12B dense",
    "kv": "q4",
    "spec": "none",
    "gb": 7.4,
    "dec": 22.7,
    "pf": 688.5,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3-coder-next-q4kxl",
    "hfRepo": "unsloth/Qwen3-Coder-Next-GGUF",
    "caps": [
      "coding"
    ],
    "params": "\u2014",
    "kv": "q4",
    "spec": "none",
    "gb": 49.6,
    "dec": 37.8,
    "pf": 716.0,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3-coder-next-reap-40b-a3b-q4kxl",
    "hfRepo": "lovedheart/Qwen3-Coder-Next-REAP-40B-A3B-GGUF",
    "caps": [
      "coding"
    ],
    "params": "40B MoE",
    "kv": "q4",
    "spec": "none",
    "gb": 28.5,
    "dec": 26.8,
    "pf": 755.5,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "Qwopus3.6-27B-Coder-MTP",
    "hfRepo": "Jackrong/Qwopus3.6-27B-Coder-MTP-GGUF",
    "caps": [
      "mtp",
      "tools"
    ],
    "params": "27B",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 22.4,
    "dec": 19.8,
    "pf": 224.5,
    "acc": 60.5,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.6-35b-a3b-q4kxl",
    "hfRepo": "unsloth/Qwen3.6-35B-A3B-GGUF",
    "caps": [],
    "params": "35B MoE",
    "kv": "q4",
    "spec": "none",
    "gb": 22.4,
    "dec": 46.1,
    "pf": 1299.8,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.6-27b",
    "hfRepo": "unsloth/Qwen3.6-27B-GGUF",
    "caps": [
      "reasoning"
    ],
    "params": "27B",
    "kv": "q4",
    "spec": "none",
    "gb": 20.0,
    "dec": 10.1,
    "pf": 299.6,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "chadrock3-6-35b-uncensored-mtp-strix-lean",
    "hfRepo": "",
    "caps": [
      "mtp"
    ],
    "params": "35B MoE",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 19.0,
    "dec": 102.1,
    "pf": 889.6,
    "acc": 86.0,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3-coder-reap-25b-a3b-q5km",
    "hfRepo": "bartowski/cerebras_Qwen3-Coder-REAP-25B-A3B-GGUF",
    "caps": [
      "coding"
    ],
    "params": "25B MoE",
    "kv": "q4",
    "spec": "none",
    "gb": 17.7,
    "dec": 54.7,
    "pf": 1367.6,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "gemma-4-26b-a4b-it-q4kxl",
    "hfRepo": "unsloth/gemma-4-26B-A4B-it-GGUF",
    "caps": [],
    "params": "26B MoE",
    "kv": "q4",
    "spec": "none",
    "gb": 17.1,
    "dec": 40.9,
    "pf": 1335.7,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.6-27b-heretic-q4km",
    "hfRepo": "DavidAU/Qwen3.6-27B-Heretic-Uncensored-FINETUNE-NEO-CODE-Di-IMatrix-MAX-GGUF",
    "caps": [
      "vision",
      "coding"
    ],
    "params": "27B",
    "kv": "q4",
    "spec": "none",
    "gb": 16.9,
    "dec": 11.6,
    "pf": 294.7,
    "acc": null,
    "note": "vision;",
    "measured": true
  },
  {
    "id": "chadrock3-6-27b-pi-agent-mtp-rocmfp4-strix-lean",
    "hfRepo": "",
    "caps": [
      "mtp"
    ],
    "params": "27B",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 14.8,
    "dec": 34.9,
    "pf": 307.7,
    "acc": 79.8,
    "note": "",
    "measured": true
  },
  {
    "id": "hermes-4-14b-q5km",
    "hfRepo": "bartowski/NousResearch_Hermes-4-14B-GGUF",
    "caps": [
      "tools"
    ],
    "params": "14B",
    "kv": "q4",
    "spec": "none",
    "gb": 10.5,
    "dec": 20.3,
    "pf": 613.6,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.5-9b-deepseek-v4-flash-mtp",
    "hfRepo": "Jackrong/Qwen3.5-9B-DeepSeek-V4-Flash-MTP-GGUF",
    "caps": [
      "mtp"
    ],
    "params": "9B",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 7.6,
    "dec": 51.3,
    "pf": 613.4,
    "acc": 69.7,
    "note": "",
    "measured": true
  },
  {
    "id": "qwopus3-5-9b-coder-mtp-q6-k",
    "hfRepo": "",
    "caps": [
      "mtp"
    ],
    "params": "9B",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 7.6,
    "dec": 44.6,
    "pf": 617.5,
    "acc": 56.0,
    "note": "",
    "measured": true
  },
  {
    "id": "gemma-4-12b-it",
    "hfRepo": "unsloth/gemma-4-12b-it-GGUF",
    "caps": [],
    "params": "12B",
    "kv": "q4",
    "spec": "none",
    "gb": 7.4,
    "dec": 22.7,
    "pf": 686.6,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "gemma4-v2-q4-k-m",
    "hfRepo": "",
    "caps": [],
    "params": "\u2014",
    "kv": "q4",
    "spec": "none",
    "gb": 7.4,
    "dec": 22.6,
    "pf": 679.8,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.5-9b-q4kxl",
    "hfRepo": "unsloth/Qwen3.5-9B-GGUF",
    "caps": [],
    "params": "9B",
    "kv": "q4",
    "spec": "none",
    "gb": 6.0,
    "dec": 33.0,
    "pf": 1044.7,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwopus3-5-4b-coder-mtp-q6-k",
    "hfRepo": "",
    "caps": [
      "mtp"
    ],
    "params": "4B",
    "kv": "q4",
    "spec": "draft-mtp",
    "gb": 3.6,
    "dec": 85.0,
    "pf": 889.2,
    "acc": 76.7,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.5-4b-q4kxl",
    "hfRepo": "unsloth/Qwen3.5-4B-GGUF",
    "caps": [],
    "params": "4B",
    "kv": "q4",
    "spec": "none",
    "gb": 2.9,
    "dec": 52.7,
    "pf": 1695.2,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3-4b-q4-k-m",
    "hfRepo": "",
    "caps": [],
    "params": "4B",
    "kv": "q4",
    "spec": "none",
    "gb": 2.5,
    "dec": 61.9,
    "pf": 1849.4,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3-zero-coder-v2-0.8b-f16",
    "hfRepo": "DavidAU/Qwen3-Zero-Coder-Reasoning-V2-0.8B-NEO-EX-GGUF",
    "caps": [
      "coding"
    ],
    "params": "0.8B",
    "kv": "q4",
    "spec": "none",
    "gb": 1.6,
    "dec": 76.3,
    "pf": 4827.2,
    "acc": null,
    "note": "",
    "measured": true
  },
  {
    "id": "qwen3.5-0.8b",
    "hfRepo": "unsloth/Qwen3.5-0.8B-GGUF",
    "caps": [],
    "params": "0.8B",
    "kv": "q4",
    "spec": "none",
    "gb": 0.6,
    "dec": 169.8,
    "pf": 6248.1,
    "acc": null,
    "note": "",
    "measured": true
  }
]
